In [1]:
import tensorflow as tf


# to run the tensorboard, open a command line and do 
#    tensorboard --logdir=../../logs
# then go to the webpage http://localhost:6006/ on your browser
logdir = "../../logs"

# Data Flow Graphs

We define a computational graph with:
* **Nodes**: operators, variables, and constants
* **Edges**: tensors. 

A computational graph is run using a *session*. 

In [22]:
def run(op, log_name="run"):
    """Utility function for running a graph and 
    output it to the tensorboard with a specific name"""
    with tf.Session() as sess:
        writer = tf.summary.FileWriter(logdir + '/{}'.format(log_name), sess.graph)
        res = sess.run(op)
        writer.close()
    return res

In [11]:
tf.reset_default_graph()
a = tf.add(3, 4)
run(a)

7

The variables are *tensors* and do not contain the result of the computation

In [5]:
a

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [12]:
tf.reset_default_graph()

x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
useless = tf.multiply(x, add_op)
pow_op = tf.pow(add_op, mul_op)
run(pow_op, 'pow_op')

15625

## Constants

In [15]:
tf.reset_default_graph()

a = tf.constant(2, name="a")
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

run(x, "constants")

5

In [17]:
tf.reset_default_graph()
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
run([x, y], "x_and_y")

[array([[2, 3],
        [4, 5]]), array([[0, 2],
        [4, 6]])]

## Tensors filled with a specific value

### Fill the tensor with zeros

In [27]:
tensor_zero = tf.zeros([2, 3], tf.int32)
tensor_zero_like = tf.zeros_like(tensor_zero)

print(tensor_zero)
print(tensor_zero_like)

Tensor("zeros_2:0", shape=(2, 3), dtype=int32)
Tensor("zeros_like_1:0", shape=(2, 3), dtype=int32)


### Fill the tensor with ones

In [28]:
tensor_one = tf.ones([2, 3], tf.int32)
tensor_one_like = tf.ones_like(tensor_one)

print(tensor_one)
print(tensor_one_like)

Tensor("ones_1:0", shape=(2, 3), dtype=int32)
Tensor("ones_like_1:0", shape=(2, 3), dtype=int32)


### Fill the tensor with specified value

In [30]:
tensor_eight = tf.fill([2, 3], 8)
print(tensor_eight)

Tensor("Fill_1:0", shape=(2, 3), dtype=int32)


## Constants and sequences

In [8]:
linspace = tf.lin_space(10.0, 13.0, 4)
linspace

<tf.Tensor 'LinSpace_2:0' shape=(4,) dtype=float32>

In [9]:
range_var = tf.range(2, 10, 3)
range_var

<tf.Tensor 'range_2:0' shape=(3,) dtype=int32>

## Random constants

In [10]:
tf.random_normal
tf.truncated_normal
tf.random_uniform
tf.random_shuffle
tf.random_crop
tf.multinomial
tf.random_gamma

<function tensorflow.python.ops.random_ops.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)>

In [13]:
tf.set_random_seed(42)

## Operations

In [19]:
tf.reset_default_graph()

a = tf.constant([2.0, 2.0], name='a', dtype=tf.float32)
b = tf.constant([[0.0, 1.0], [2.0, 3.0]], name='b', dtype=tf.float32)
with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))             
    print(sess.run(tf.divide(b, a)))          
    print(sess.run(tf.truediv(b, a)))         
    print(sess.run(tf.floordiv(b, a)))        
#     print(sess.run(tf.realdiv(b, a)))      #---> not working for me :(
#     print(sess.run(tf.truncatediv(b, a)))  #---> not working for me :(   
    print(sess.run(tf.floor_div(b, a)))       


[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0. 0.]
 [1. 1.]]
[[0. 0.]
 [1. 1.]]


## Variables

In [23]:
tf.reset_default_graph()


# create variables with tf.Variable
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))

# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

`tf.Variable` holds several ops:

```
x = tf.Variable(...) 

x.initializer # init op
x.value() # read op
x.assign(...) # write op
x.assign_add(...) # and more
```


In [31]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())  # we have to intialize the variables, before using them
    print(sess.run(W))
    assignment_op = W.assign(tf.ones_like(W))
    print(sess.run(assignment_op))
    print(W.eval())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [33]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var") 

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    print(sess.run(my_var.initializer))
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two)) # be careful, the assignment continues to assigning to my_var every time
    print(sess.run(my_var_times_two)) # be careful, the assignment continues to assigning to my_var every time

None
4
8
16


## Each session maintains its own copy of variables


In [35]:
tf.reset_default_graph()


W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))\

20
8


## Placeholders

In [41]:
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])

b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant or a variable
c = a + b  # short for tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a: [1, 2, 3]}))

[6. 7. 8.]
